version: "3"

services:
   ping:
    build: ./ping
    container_name: ping
    hostname: ping
    restart: always
    ports:
      - "5000:5000"
    links:
      - pong
   pong:
    build: ./pong
    container_name: pong
    hostname: pong
    restart: always
    ports:
      - "5001:5001"
